[package]
name = "UDTool"
version = "1.0.0"
edition = "2024"
authors = ["Ari Cummings <ari@aricummings.com>"]



[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.12", features = ["blocking", "json", "multipart"] }
